# Generated by Django 6.0.5 on 2026-05-11 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Food', 'Food'), ('Beauty', 'Beauty'), ('Tech', 'Tech')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('profile_image', models.ImageField(upload_to='profile_photos/')),
                ('cover_image', models.ImageField(upload_to='cover_photos/')),
                ('is_premium', models.BooleanField(default=False)),
                ('has_used_trial', models.BooleanField(default=False)),
                ('trial_start_date', models.DateTimeField(blank=True, null=True)),
                ('premium_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_auth_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plugs.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor_photos/')),
                ('caption', models.CharField(blank=True, help_text='E.g. Vintage Jacket - ₦5,000', max_length=100)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='plugs.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorNiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. Vintage Denim, UK Used iPhones', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='niche_photos/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niches', to='plugs.vendor')),
            ],
        ),
    ]
