# Generated by Django 6.0.5 on 2026-05-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Food', 'Food'), ('Beauty', 'Beauty'), ('Hair & Wigs', 'Hair & Wigs'), ('Real Estate', 'Real Estate'), ('Automobiles', 'Automobiles'), ('Tech', 'Tech'), ('Home & Decor', 'Home & Decor'), ('Events & Printing', 'Events & Printing'), ('Health & Fitness', 'Health & Fitness')], max_length=50),
        ),
    ]
