# Generated by Django 6.0.5 on 2026-05-19 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugs', '0002_vendor_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VendorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.EmailField(max_length=254)),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='plugs.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'buyer_email')},
            },
        ),
    ]
