# Generated by Django 6.0.5 on 2026-05-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugs', '0003_vendor_is_active_vendor_report_count_vendorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorreport',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Optional: Upload a screenshot of the chat as proof', null=True, upload_to='report_evidence/'),
        ),
    ]
