# Generated by Django 6.0.5 on 2026-05-26 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugs', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='instagram_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rank_score',
            field=models.IntegerField(default=0, help_text='CEO Override: 0=Normal, 999=Pinned Top, -999=Buried Bottom'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='whatsapp_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Amount in kobo (e.g. 4000000 for ₦40k)')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugs.vendor')),
            ],
        ),
    ]
