# Generated by Django 6.0.5 on 2026-05-28 23:44

import plugs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugs', '0006_vendor_instagram_clicks_vendor_rank_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(help_text='Amount in kobo (e.g. 2000000 for ₦20k)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/', validators=[plugs.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[plugs.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='vendorgallery',
            name='image',
            field=models.ImageField(upload_to='vendor_photos/', validators=[plugs.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='vendorniche',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='niche_photos/', validators=[plugs.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='vendorreport',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Optional: Upload a screenshot of the chat as proof', null=True, upload_to='report_evidence/', validators=[plugs.validators.validate_image_file]),
        ),
    ]
